version: "3.7"
services:
  postgres:
    image: postgres:12.1-alpine
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis:5-alpine
    ports:
      - "127.0.0.1:6379:6379"
